language: php
php:
  - 5.5
  - 5.6
install:
  - composer install
before_script:
  - php --version
  - mkdir -p build/coverage

script:
  - phpunit --coverage-php build/coverage/coverage.cov

after_script:
  - php vendor/bin/phpcov merge --clover build/logs/clover.xml build/coverage
  - php vendor/bin/coveralls